### ISSUE TITLE
Minor soundness issue with Decoder's Send trait

### ISSUE THREAD

**Issue by ammaraskar** [mvertescher/libsbc-rs#4]
The `Send` trait for `Decoder` should probably be `R: Read + Sync` here:

https://github.com/mvertescher/libsbc-rs/blob/7278b23901f93d956d9739fdfc4ced147cc3f242/src/lib.rs#L34-L38

otherwise it's possible to send `Read` instances across threads that might not support it. For example `std::io::StdinLock` is a `Read` but is not `Send`. However, wrapping it in a `Decoder` allows it to be sent across threads:

```rust
use libsbc::Decoder;

use std::io;
use static_assertions::{assert_not_impl_all, assert_impl_all};

fn main() {
    assert_not_impl_all!(io::StdinLock : Send);
    assert_not_impl_all!(Decoder<io::StdinLock> : Send);
}
```

fails with an assertion error because `Send` is implemented. (Issue found by @sslab-gatech's Rust group)

**Comment by mvertescher** [comment]
Interesting, thanks for reporting this! Sounds like a serious issue to me, we should add `+ Sync` to `Decoder`.

**Comment by qwaz** [comment]
Wouldn't be the correct bound `R: Read + Send`?

**Comment by ammaraskar** [comment]
Err yes, it actually should be `+ Send`, not sure why I wrote Sync there 😅
